# Generated by Django 5.0.7 on 2024-07-15 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email_Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Email Template',
            },
        ),
        migrations.CreateModel(
            name='Document_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='EmailDocuments/')),
                ('email_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_templater.email_template')),
            ],
            options={
                'verbose_name': 'Image File',
            },
        ),
    ]
