# Generated by Django 5.0.7 on 2024-07-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_templater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_template',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
