# Generated by Django 5.0.7 on 2024-07-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_templater', '0002_email_template_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_template',
            name='contains_attachment',
            field=models.BooleanField(default=False),
        ),
    ]
