# Generated by Django 5.0.7 on 2024-08-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_templater', '0003_email_template_contains_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_template',
            name='external_links',
            field=models.JSONField(default=list),
        ),
    ]
