# Generated by Django 5.0.7 on 2024-08-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_templater', '0005_alter_email_template_external_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_template',
            name='external_links',
            field=models.JSONField(default={}),
        ),
    ]
