# Generated by Django 5.0.7 on 2024-08-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_templater', '0009_alter_email_template_external_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_template',
            name='email_recipients',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
