# Generated by Django 5.0.7 on 2024-08-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_templater', '0010_email_template_email_recipients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document_file',
            options={'verbose_name': 'Attachment'},
        ),
        migrations.AddField(
            model_name='email_template',
            name='template_type',
            field=models.CharField(default='task', max_length=60),
            preserve_default=False,
        ),
    ]
