# Generated by Django 5.0.7 on 2024-08-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_templater', '0011_alter_document_file_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_template',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='Banner/'),
        ),
    ]
